# Generated by Django 5.2.1 on 2025-05-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
